apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: kong
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
      labels:
        app: user-service
        version: "1"
    spec:
      containers:
        - name: user-service
          image: codydearkland/user-service:beta3
          env:
            - name: MESH_TYPE
              value: "kuma" # Update me to your service mesh, 'kong-mesh' or 'kuma' or blank for none
            - name: MESH_NS
              value: "kuma-system" # Update me to your Kuma/Kong Mesh NS or leave blank
            - name: secret_key
              value: "hkBxrbZ9Td4QEwgRewV6gZSVH4q78vBia4GBYuqd09SsiMsIjH"
            - name: POSTGRES_HOST
              value: "db_kong_svc_5432.mesh"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres_password"
            - name: POSTGRES_PORT
              value: "80"
            - name: POSTGRES_DATABASE
              value: "posts"
            - name: LC_ALL
              value: "C.UTF-8"
            - name: LANG
              value: "C.UTF-8"
            - name: fernet
              value: "TqwnupPqap-UCpNCR70KADvdtVnW0fhcFlni8muk9sQ="
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: kong
  annotations: 
    "5000.service.kuma.io/protocol": "http"
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service
  namespace: kong
  labels:
    app: posts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
      labels:
        app: posts-service
        version: "1"
    spec:
      containers:
        - name: posts-service
          image: codydearkland/posts-service:beta5
          env:
            - name: MESH_TYPE
              value: "kuma" # Update me to your service mesh, 'kong-mesh' or 'kuma' or blank for none
            - name: MESH_NS
              value: "kuma-system" # Update me to your Kuma/Kong Mesh NS or leave blank
            - name: REDIS_HOST
              value: "redis_kong_svc_6379.mesh"
            - name: REDIS_PORT
              value: "80"
            - name: secret_key
              value: "hkBxrbZ9Td4QEwgRewV6gZSVH4q78vBia4GBYuqd09SsiMsIjH"
            - name: POSTGRES_HOST
              value: "db_kong_svc_5432.mesh"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres_password"
            - name: POSTGRES_PORT
              value: "80"
            - name: POSTGRES_DATABASE
              value: "posts"
            - name: LC_ALL
              value: "C.UTF-8"
            - name: LANG
              value: "C.UTF-8"
            - name: fernet
              value: "TqwnupPqap-UCpNCR70KADvdtVnW0fhcFlni8muk9sQ="
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
  namespace: kong
  annotations:
    "5000.service.kuma.io/protocol": "http"
spec:
  selector:
    app: posts-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontreact
  namespace: kong
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
      labels:
        app: react
    spec:
      containers:
        - name: frontreact
          image: codydearkland/demo-react:v2
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontreact
  namespace: kong
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    80.service.kuma.io/protocol: http
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: kong
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: codydearkland/db-tier:latest
          ports:
            - containerPort: 5432
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: kong
  annotations:
    "80.service.kuma.io/protocol": "http"
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kong
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kong
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
