apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata: 
  name: allow-demoapp
spec: 
  sources: 
    - match: 
        group: 'demoapp'
  destinations: 
    - match: 
        group: 'demoapp'
