apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata: 
  name: posts-redis
spec: 
  sources: 
    - match: 
        kuma.io/service: 'posts-service_kong_svc_5000'
  destinations: 
    - match: 
        kuma.io/service: 'redis_kong_svc_6379'
