apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata: 
  name: posts-postgres
spec: 
  sources: 
    - match: 
        kuma.io/service: 'posts-service_kong_svc_5000'
    - match:
        kuma.io/service: 'user-service_kong_svc_5000'
  destinations: 
    - match: 
        kuma.io/service: 'db_kong_svc_5432'
