apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: http-users-route
spec:
  sources:
    - match:
        kuma.io/service: 'kong-proxy_kuma-gateway_svc_80'
  destinations:
    - match:
        kuma.io/service: 'posts-service_kong_svc_5000'
  conf:
    http:
    - match:
        path:
          prefix: "/api/posts"
      destination:
        kuma.io/service: posts-service_kong_svc_5000
    destination:
      kuma.io/service: '*'
