apiVersion: kuma.io/v1alpha1    
kind: TrafficRoute      
mesh: default           
metadata:               
  name: route-health    
  namespace: test-server    
spec:                   
  sources:              
  - match:                      
      kuma.io/service: '*'    
  destinations:         
  - match:                      
      kuma.io/service: '*'    
