apiVersion: kuma.io/v1alpha1
kind: OPAPolicy
mesh: default
metadata:
  name: opa-1
spec:
  selectors:
  - match:
      kuma.io/service: '*'
  conf:
    agentConfig: # optional
      inlineString: | # one of: inlineString, secret
        decision_logs:
          console: true
    policies: # optional
      - inlineString: | # one of: inlineString, secret
          package envoy.authz
          import input.attributes.request.http as http_request
          default allow = false
          token = {"valid": valid, "payload": payload} {
              [_, encoded] := split(http_request.headers.authorization, " ")
              [valid, _, payload] := io.jwt.decode_verify(encoded, {"secret": "hkBxrbZ9Td4QEwgRewV6gZSVH4q78vBia4GBYuqd09SsiMsIjH"})
          }
          
          allow {
            action_allowed
          }

          allow { 
            post_allowed
          }

          allow {
            login_allowed
          }

          allow {
            delete_posts
          }

          login_allowed {
            http_request.method == "POST"
            input.attributes.request.http.path = "/api/loginEndpoint"
          }

          action_allowed {
            http_request.method == "GET"
          }

          post_allowed {
            http_request.method == "POST" 
            token.payload.user_id == "cody"
          }

          delete_posts {
            http_request.method == "DELETE"
            token.payload.user_id == "cody"
          }





          

