apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: route-example
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: frontreact_kong_svc_80
  conf:
    split:
      - weight: 100
        destination:
          kuma.io/service: frontreact_kong_svc_80
          color: light
      - weight: 0
        destination:
          kuma.io/service: frontreact_kong_svc_80
          color: dark
